vich_uploader:
  db_driver: orm

  mappings:
    uploaded_image:
      #nom du mapping
      uri_prefix:
        '/img/uploaded_images'
        #Je récupère le chemin du dossier dans lequel je vais stocker les images à téléverser
      upload_destination: '%kernel.project_dir%/public/build/img%uploaded_images%'
      namer:
        Vich\UploaderBundle\Naming\SmartUniqueNamer
        # SmartUniqueNamer va rajouter des éléments au nom du fichier pour éviter de créer des doublons
